settings:
  title: '상태 페이지'
  url: 'https://status.yems.kr' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 100 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: yems-kr
    name: YEMS
    description: '공식 홈페이지' # default=empty
    url: 'https://yems.kr/'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: blog-yems-kr
    name: Blog
    description: '블로그' # default=empty
    url: 'https://blog.yems.kr/'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: i-yems-kr
    name: Images
    description: '이미지 업로드용 클라우드 스토리지' # default=empty
    url: 'https://i.yems.kr/'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: obsdn-yems-kr
    name: Obsidian
    description: '옵시디언' # default=empty
    url: 'https://obsdn.yems.kr/'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: static-obsdn-yems-kr
    name: 'Obsidian Photos'
    description: '옵시디언 문서 내 사진에 사용되는 클라우드 스토리지' # default=empty
    url: 'https://static-obsdn.yems.kr/'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: status-yems-kr
    name: Status
    description: '상태 페이지' # default=empty
    url: 'https://status.yems.kr/'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
